[package]
name = "paq"
version = "0.1.0"
authors = ["programingjd"]
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[features]
#default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
#console_error_panic_hook = "0.1"
mashi-core = "0.1"

[profile.release]
opt-level = "s"
lto = true
